[package]
name = "rlrcget"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
color-eyre = "0.6.5"
config = "0.15.17"
crossterm = "0.29.0"
lofty = "0.22.4"
ratatui = "0.29.0"
rodio = "0.21.1"
serde = { version = "1.0.227", features = ["derive"] }
walkdir = "2.5.0"
